######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 21 13:08:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qt.h
SOURCES += qt.cpp
RESOURCES += qt.qrc
